### ISSUE TITLE
Compilation error on debian?

### ISSUE THREAD

**Issue by ThijsWithaar** [intel/compute-runtime#16] opened 2018-02-17 07:10 UTC
When compiling on debian buster, using clang 5.0.1-2, the make step give me:
```
Scanning dependencies of target igfx_gmmumd_excite
[  1%] Building CXX object gmmlib/Source/GmmLib/CMakeFiles/igfx_gmmumd_excite.dir/__/Common/AssertTracer/AssertTracer.cpp.o
clang: error: unknown argument: '-fno-tree-pre'
clang: warning: -Wl,--no-undefined: 'linker' input unused [-Wunused-command-line-argument]
```

Are there some compile settings I should change ?

**Comment by ArturHarasimiuk** [comment] 2018-02-19 18:54
We have looked into this and it appears the problem is in [GmmLib](https://github.com/intel/gmmlib) component. We have filed an issue there [link](https://github.com/intel/gmmlib/issues/7).

**Comment by MichalMrozek** [comment] 2018-02-22 07:36
Looks like problem is fixed in gmmlib.
Closing this one.

**Closed by MichalMrozek** 2018-02-22 07:36 UTC
